### ISSUE TITLE
No images found 17/6/24

### ISSUE THREAD

**Issue by kryanhinds** [thespacedoctor/panstamps#13] opened 2024-06-17 08:34 UTC
I'm trying to download some images from the server and I'm getting the following error:

* 09:24:35 - WARNING: /home/arikhind/miniconda3/envs/ltsub/lib/python3.11/site-packages/panstamps/downloader.py:get:236 > No images found. Your options may not be set correctly. Here's the requested URL:
http://ps1images.stsci.edu/cgi-bin/ps1cutouts?pos=224.17479166666664+16.84069722222222&filter=g&filetypes=stack&size=5492&output_size=5492&verbose=0&autoscale=99.500000&catlist=

I haven't had this error before and the image seems fine. Any guidance?

**Comment by thespacedoctor** [comment] 2024-06-17 13:12
There was a recent change to the HTML of the ps1images pages. Can you let me know what version of panstamps you are running?

**Comment by kryanhinds** [comment] 2024-06-17 14:50
Thanks for the quick reply, I'm using v0.6.7!

**Comment by thespacedoctor** [comment] 2024-06-18 16:18
Can you send me the command line request you are making, and I will try and reproduce the error?

**Comment by kryanhinds** [comment] 2024-06-19 08:22
This was the command:

 ~/miniconda3/envs/ltsub/bin/panstamps -f --width=22.883795000000006 --filters=g stack 224.17479166666664 16.84069722222222

**Comment by thespacedoctor** [comment] 2024-06-20 10:38
Hi @kryanhinds. @genghisken and I have run this command and cannot reproduce the error with v0.6.7 of panstamps on either of our machines.

I think the errors occur with v0.6.6 and below, so can you please double-check that you have the correct version installed?

Thanks!

**Comment by genghisken** [comment] 2024-06-20 10:39
I'm also running panstamps 0.6.7. Running the command above seems to work OK for me (Ubuntu 22.04, python 3.7.16)

```
panstamps -f --width=22.883795000000006 --filters=g stack 224.17479166666664 16.84069722222222
  1 / 1 (100.0%) URLs downloaded
```

I also created a new python 3.11 environment and installed panstamps.  All ran OK.

**Comment by thespacedoctor** [comment] 2024-06-26 07:44
Closing this now @kryanhinds , but please re-open if you are still having problems.

**Closed as completed by thespacedoctor** 2024-06-26 07:44 UTC
